### ISSUE TITLE
[error] mac and sass build

### ISSUE THREAD

**Issue by mavogel** [bekkere/docker-ionic2#2]
Thanks for the docker image dude!

1. For me to get this to work I had to fix the ports to
`alias ionic2Docker="docker run -ti --rm -p 8101:8100 -p 35730:35729 -v \$PWD:/myApp:rw bekkere/docker-ionic2:latest ionic"`
because I always got. And there is no process running on 35729. Checked `docker ps -a`
```bash
$ ionic2Docker serve --lab -b
docker: Error response from daemon: driver failed programming external connectivity on endpoint brave_shaw (ab16398bc9a00a466c6a34f814856182a621505845f95d1b2432104868af7f93): Error starting userland proxy: Bind for 0.0.0.0:35729 failed: port is already allocated.
```

2. Ok I got this fixed. But when I now run `ionic2Docker serve --lab -b` I get
```bash
Error: Missing binding /myApp/node_modules/node-sass/vendor/linux-x64-51/binding.node
Node Sass could not find a binding for your current environment: Linux 64-bit with Node.js 7.x

Found bindings for the following environments:
  - OS X 64-bit with Node.js 6.x
```
which is currently installed on my machine.

- Do you think it's even possible to run this on my mac or a windows machine? 
- What environment do you have on your local machine to test the container?

Thanks and regards Manu

**Comment by bekkere** [comment]
Hi Manu

Apologies for the delay in response. 
To perform a test on my side, I completely removed my local container and created a new solution from scratch.

I am running on a macbook and also a imac .... did not face any of the issues you ran into above.
From the look of things, the first issues your facing looks like a local port conflict... so you have something else already running on that port? 
Do you perhaps have another ionic container running? (docker ps -a)

Not sure about your second issue... I am unable to troubleshoot as I dont have the issue.
have you tried npm rebuild node-sass?

**Comment by mavogel** [comment]
Hi bekkere,

thank you for you answer and sorry for my delay. First of all: your solution works fine! 
I had a misleading thought running `npm install` outside of the container. So sure `sass` made problems, cuz it was compiled on osx and then mounted into the container ;-)

Some issues I could solve where the livereload by passing through the `53703` port as well. Additionally I added the `-d` parameter the detach the container after startup. This was necessary because `CTRL-C` did not work to get out of the container. I had to open another terminal and `docker stop` the container like this. To get the logs anyway, I ran `docker logs -tf ...`.

So my final command was:
`alias ionic2Docker="docker run -tid --rm -p 8101:8100 -p 35730:35729 -p 53703:53703 -v \$PWD:/myApp:rw bekkere/docker-ionic2:latest ionic"` 

One final question: did you ever try to run this command on windows? Like gitbash or powershell?

Thank you very much for the good work.
Regards Manu

**Comment by bekkere** [comment]
Hi Manu
I use my bash profile and docker functions script across my Ubuntu, Mac and Windows machines.
For the most part, things work across all 3 platforms... the main issue I always face is down to the volumes on the windows machine.... I always have to adjust play and adjust the -v on the alias for the windows machine, and find i can only get the volumes correctly working when in my Users/home folder...

Once I get this mounting the volumes correctly, everything works the same across my machines... fyi, I am still running Docker-Toolbox on my windows, as I cant afford not to have virtualbox... i have not tried with the Docker for Windows...

Hope this helps...

**Comment by mavogel** [comment]
Thank you for the hint! 
Would you mind, sharing these functions (especially on Windows) with me and tell me which shell you use on Windows? That would help me a lot =)

**Comment by bekkere** [comment]
Hey Manu
I will add you to one of my private repos .... please feel free to download and use. Suggest you verify some of the functions, as they are set up for usage across my machines.... you will also find a .dockerfunc file i use to containerize my apps/frameworks...

The shell i use on windows machines are: Babun and the Docker CLI shell.
I prefer Mac and Linux over windows, so dont do much with windows tools.... 

Cheers
Ettiene

**Comment by bekkere** [comment]
Hi Manu

Was just checking the content of my private repo i shared with you.... happy for you to copy and use, just be warned this will change your terminal.... so suggest you make backup copies of your existing files before you update your bash_aliases file....

Another word of warning, i update this frequently, sometimes with breaking changes .... so i suggest you make a copy and let me know once done.

Let me know if you want me to explain anything you find in the files....  

Cheers
Ettiene

**Comment by mavogel** [comment]
Alright thanks! You mean the `.dockerfunc` linked in the README of https://github.com/bekkere/dockerfiles ? Cuz I didn't get any notification for being added to a private repo.

**UPDATE:** got an invitation ... hehe so everything's fine. Thanks man!

**Comment by bekkere** [comment]
Hi Manu

Update: I tried today to run this on my windows machine, but ran into multiple issues.
I will look at this in future, as I dont have time at the moment.
